from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DEMO_DIR = PROJECT_ROOT / "demo"
DEMO_IMAGES_DIR = DEMO_DIR / "images"
DEMO_VIDEOS_DIR = DEMO_DIR / "videos"

OUTPUTS_DIR = PROJECT_ROOT / "outputs"
OUTPUT_IMAGES_DIR = OUTPUTS_DIR / "images"
OUTPUT_VIDEOS_DIR = OUTPUTS_DIR / "videos"

DEFAULT_RESIZE_WIDTH = 640
DEFAULT_VIDEO_RESIZE_WIDTH = 640
DEFAULT_COMPRESS_WIDTH = 640
DEFAULT_COMPRESS_FPS = 10
DEFAULT_MAX_DURATION = 20
DEFAULT_CRF = 28

DEFAULT_HIT_THRESHOLD = 0.0
DEFAULT_SCALE = 1.05
DEFAULT_NMS_THRESHOLD = 0.35
DEFAULT_MAX_DETECTIONS = 10
DEFAULT_FRAME_SKIP = 3

DEFAULT_WEBCAM_RESIZE_WIDTH = 480
DEFAULT_WEBCAM_HIT_THRESHOLD = 0.5
DEFAULT_WEBCAM_SCALE = 1.1
DEFAULT_WEBCAM_NMS_THRESHOLD = 0.25
DEFAULT_WEBCAM_FRAME_SKIP = 3
DEFAULT_WEBCAM_MAX_DETECTIONS = 5

REQUIRED_DIRECTORIES = [
    DEMO_IMAGES_DIR,
    DEMO_VIDEOS_DIR,
    OUTPUT_IMAGES_DIR,
    OUTPUT_VIDEOS_DIR,
]


def ensure_project_structure() -> None:
    for directory in REQUIRED_DIRECTORIES:
        directory.mkdir(parents=True, exist_ok=True)


ensure_project_structure()
